const SEARCH_HITTERS = "SEARCH_HITTERS";
const GET_HITTER_YEAR = "GET_HITTER_YEAR";
const SEARCH_PITCHERS = "SEARCH_PITCHERS";
const GET_PITCHER_YEAR = "GET_PITCHER_YEAR";

const CLEAR_PLAYERS = "CLEAR_PLAYERS";
const CLEAR_YEAR = "CLEAR_YEAR";

const SET_LOADING = "SET_LOADING";
